# -*- coding: utf-8 -*-
"""LVADSUSR138_Abhishek_Meena_Lab4_Anomaly_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOqEL7pNwVeWsRbDoUvJ8JXTN8aWUbym
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest

data = pd.read_csv("/content/anomaly_train.csv")

"""explatory data analysis"""

data.shape

data.describe()

data.info()

"""null and duplicate values"""

print("Null values:")
print(data.isnull().sum())

print("Number of duplicate rows:", data.duplicated().sum())
data = data.drop_duplicates()
print("Number of duplicate rows after dropping:", data.duplicated().sum())

"""scatter plot for numerical data"""

plt.figure(figsize=(12, 6))
sns.scatterplot(x='Amount', y='Time', data=data)
plt.title('Scatter Plot of Amount vs. Time')
plt.xlabel('Amount')
plt.ylabel('Time')
plt.show()

"""numerical and categorical features"""

numerical_features = ['Amount', 'Time', 'User']

data = pd.get_dummies(data, columns=['Type', 'Location'])

"""training the model and predicting outliers"""

numerical_data = data[numerical_features]

model = IsolationForest(contamination=0.05)
model.fit(numerical_data)

outliers = model.predict(numerical_data)

data['IsOutlier'] = outliers

"""printing the anomalies"""

num_anomalies = (outliers == -1).sum()
print("Number of anomalies detected:", num_anomalies)

anomalies = data[data['IsOutlier'] == -1]

"""scatter plot"""

plt.figure(figsize=(12, 6))
sns.scatterplot(x='Amount', y='Time', hue='IsOutlier', data=data)
plt.title('Scatter Plot of Amount vs. Time (Anomalies)')
plt.xlabel('Amount')
plt.ylabel('Time')
plt.show()

print("Anomalies:")
print(anomalies)