# -*- coding: utf-8 -*-
"""LVADSUSR138_Abhishek-Meena.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZ8w3DNkTK2eqfQikQF_Gqz3An96jkZ4
"""

#question1
print('length :')
length = int(input())
print('width :')
width = int(input())

area = length * width
print('Area:', area)

if area<10:
  print('small')
elif area>=10 and area<100:
  print('medium')
else:
  print('large')

#question2
print('weight in kgs:')
weight = float(input())
print('height in meters:')
height = float(input())
print('your BMI is:', weight/(height*height))

#question3

dict1 = {'abhishek': None, 'rishabh': None, 'vishal': None}
for i in dict1.keys():
  print('Enter marks:', i)
  dict1[i] = input()
print(dict1)

#question4
print('Enter age:')
age = int(input())
if age<11:
  print('children')
elif age>=11 and age<18:
  print('teen')
elif age>=18 and age<30:
  print('adult')
else:
  print('senior')

#question5

list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
ans = []
for i in range(len(list1)):
  if list1[i]%2==0:
    ans.append(list1[i])
print(ans)

#question6
dict1 = {'abhishek.meena@latentview.com': 12345}
password = int(input())

if dict1['abhishek.meena@latentview.com'] != password:
    print('try again wrong password')
else:
  print('Welcome Abhishek! Logging in')

#question7
def analyze(feedback_score):
  avg = 0
  for i in range(len(feedback_score)):
    avg += feedback_score[i]
  avg = float(avg/len(feedback_score))
  return avg

feedback_score = [4, 5, 1, 2, 1, 5, 5, 3, 2, 3]
print('average feedback score is:' , analyze(feedback_score))
if analyze(feedback_score) <3:
  print('bad feedback')
elif analyze(feedback_score) ==3:
  print('okay feedback')
else:
  print('good feedback')

#question8
def countv(str1):
  count = 0
  for i in range(len(str1)):
    if str1[i] == 'a' or str1[i] == 'e' or str1[i] == 'i' or str1[i] == 'o' or str1[i] == 'u':
      count +=1
  return count

str1 = input()
print('total vowels are: ', countv(str1))

#question9
print('Enter date:')
date = int(input())
print('Enter time in hrs:')
time = int(input())

if date >=1 and date <10:
  print('starting of the month')
elif date >=10 and date <20:
  print('middle of the month')
else:
  print('month is going to end soon')

if time >=9 and time <=15:
  print('office hours')
else:
  print('not office hours')

#question10
print('Enter loan amount:')
loan = int(input())
print('Enter interest rate in percent')
interest = int(input())
print('Enter amount already paid:')
amount = int(input())
print('Amount left:', loan+loan*interest/100 - amount)

#question11
print('Enter name: ')
name = input()
print('Enter age: ')
age = int(input())
print('Enter profession: ')
prof = input()

#question12
print('Enter num1: ')
num1 = int(input())
print('Enter num2: ')
num2 = int(input())
print('Addition: ')
print(num1+num2)
print('Subtraction: ')
print(num1-num2)
print('Multiplication: ')
print(num1*num2)
print('Division: ')
try:
  print(num1/num2)
except:
  print('error')

#question13

prev = [1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1]
print('Enter daily status :')
daily = int(input())
prev.append(daily)
print('daily uptime status including today', prev)
if daily == 1:
  print('system is fine')
else:
  print('system error')

#question14
print('enter log file input: ')
log_1 = int(input())
if log_1 == 1:
  print('Everything okay')
else:
  print('System error')

#question15
company_news = ['nice', 'okay', 'good']
stock_performance = ['good', 'bad', 'okay']
industry_news = ['bad', 'worse', 'good']

print('Enter company news:')
news = input()
company_news.append(news)

print('Enter stock_performance:')
stock = input()
stock_performance.append(stock)

print('Enter industry_news:')
indus = input()
industry_news.append(indus)

print(company_news)
print(stock_performance)
print(industry_news)