# -*- coding: utf-8 -*-
"""LVADSUSR138_Abhishek_Meena-Predictive_IA1_logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_h7lYpxxP1YjJgCNlaCnMPyQkNjCmCsf
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score

df = pd.read_csv('/content/booking.csv')
df

df.info()

df.shape

df.describe()

#question 1.1
df.isnull().sum()

#question 1.1
avg_out_price = sns.boxplot(df['average price'])
df = df[df['average price']<225]

lead_time_out = sns.boxplot(df['lead time'])
df = df[df['lead time']<330]

df.info()

#question 1.2
label = LabelEncoder()
df['room type'] = label.fit_transform(df['room type'])
df['type of meal'] = label.fit_transform(df['type of meal'])
df['booking status'] = label.fit_transform(df['booking status'])
df['market segment type'] = label.fit_transform(df['market segment type'])

#question 1.3
plt.scatter(df['number of children'],df['average price'])

plt.scatter(df['number of adults'],df['average price'])

plt.scatter(df['number of week nights'],df['average price'])

df = df.drop(columns=['Booking_ID', 'date of reservation'],axis=1)

df.duplicated().sum()

df.drop_duplicates()

#question 1.4, 1.5
X = df.drop('booking status',axis=1)
y = df['booking status']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=45)

reg = LogisticRegression(max_iter=15000)
model = reg.fit(X_train,y_train)
y_pred = model.predict(X_test)

#question 1.6
acc = accuracy_score(y_test,y_pred)
pre = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)

print('Accuracy score of the model is: ',round(acc*100,2),'%')
print('Precision score of the model is: ',round(pre*100,2),'%')
print('Recall score of the model is: ',round(re*100,2))