# -*- coding: utf-8 -*-
"""LVADSUSR138_Abhishek_Meena-Predictive_IA1_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZLjQNq1twl87RfnUmPtYW9b1l0vcSYD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv('/content/expenses.csv')

df

df.shape

df.info()

df.describe()

#question 1.1
df.isnull().sum()

#question 1.1
age_outl = sns.boxplot(df['age'])

bmi_outl = sns.boxplot(df['bmi'])

children_outl = sns.boxplot(df['children'])

charges_outl = sns.boxplot(df['charges'])

print(df[df['charges']>45000].count())

def remove_outl(a, b):
  return df[a<b]

df = remove_outl(df['charges'],45000)
df = remove_outl(df['bmi'],45)
df.count()

df.info()

#question 1.2
label = LabelEncoder()
df['sex'] = label.fit_transform(df['sex'])
df['smoker'] = label.fit_transform(df['smoker'])
df['region'] = label.fit_transform(df['region'])

df

#question 1.3
df.duplicated().sum()

sns.pairplot(df)

#question 1.4, 1.5
X = df.drop('charges',axis=1)
y = df['charges']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

reg = LinearRegression()
model = reg.fit(X_train,y_train)
y_pred = model.predict(X_test)

#question 1.6
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

print('Mean square error is: ',mse)
print('Root mean square error is: ',rmse)
print('R-Squared value is: ',r2)